pair_output: ../data/xml_output/HCRMAAAAcAAJ.xml \
			 ../data/xml_output/3pVMAAAAcAAJ.xml \
			 ../data/xml_output/D5pMAAAAcAAJ.xml \
			 ../data/xml_output/7JVMAAAAcAAJ.xml \
			 ../data/xml_output/AdiKyqdlp4cC.xml \
			 ../data/xml_output/_QgOAAAAQAAJ.xml \
			 ../data/xml_output/fAoOAAAAQAAJ.xml \
			 ../data/xml_output/wggOAAAAQAAJ.xml \
			 ../data/xml_output/kggOAAAAQAAJ.xml \
			 ../data/xml_output/PzMJAAAAQAAJ.xml \
			 ../data/xml_output/1VUJAAAAQAAJ.xml \
			 ../data/xml_output/rDUJAAAAQAAJ.xml \
			 ../data/xml_output/MzQJAAAAQAAJ.xml \
			 ../data/xml_output/Fy4JAAAAQAAJ.xml \
			 ../data/xml_output/YAZXAAAAcAAJ.xml \
			 ../data/xml_output/8AQoAAAAYAAJ.xml \
			 ../data/xml_output/J4knAAAAMAAJ.xml \
			 ../data/xml_output/2jMfAAAAMAAJ.xml \
			 ../data/xml_output/u4cnAAAAMAAJ.xml \
			 ../data/xml_output/4zQfAAAAMAAJ.xml \
			 ../data/xml_output/WjMfAAAAMAAJ.xml \
			 ../data/xml_output/zviTtwEACAAJ.xml \
			 ../data/xml_output/zDTMtgEACAAJ.xml \
			 ../data/xml_output/quentindurward01scotuoft.xml \
			 ../data/xml_output/quentindurward02scotuoft.xml \
			 ../data/xml_output/chroniclesofcano02scot.xml \
			 ../data/xml_output/chroniclesofcano03scot.xml \
			 ../data/xml_output/anneofgeierstein02scot.xml \
			 ../data/xml_output/anneofgeierstein03scot.xml \
			 ../data/xml_output/XtEyAQAAMAAJ.xml \
			 ../data/xml_output/8dAyAQAAMAAJ.xml \
			 ../data/xml_output/oNEyAQAAMAAJ.xml \
			 ../data/xml_output/t88yAQAAMAAJ.xml \
			 ../data/xml_output/aNQwAQAAMAAJ.xml \
			 ../data/xml_output/htQwAQAAMAAJ.xml \
			 ../data/xml_output/DNUwAQAAMAAJ.xml \
			 ../data/xml_output/H9UwAQAAMAAJ.xml \
			 ../data/pdf_renamed/HCRMAAAAcAAJ.pdf \
			 ../data/pdf_renamed/3pVMAAAAcAAJ.pdf \
			 ../data/pdf_renamed/D5pMAAAAcAAJ.pdf \
			 ../data/pdf_renamed/7JVMAAAAcAAJ.pdf \
			 ../data/pdf_renamed/AdiKyqdlp4cC.pdf \
			 ../data/pdf_renamed/_QgOAAAAQAAJ.pdf \
			 ../data/pdf_renamed/fAoOAAAAQAAJ.pdf \
			 ../data/pdf_renamed/wggOAAAAQAAJ.pdf \
			 ../data/pdf_renamed/kggOAAAAQAAJ.pdf \
			 ../data/pdf_renamed/PzMJAAAAQAAJ.pdf \
			 ../data/pdf_renamed/1VUJAAAAQAAJ.pdf \
			 ../data/pdf_renamed/rDUJAAAAQAAJ.pdf \
			 ../data/pdf_renamed/MzQJAAAAQAAJ.pdf \
			 ../data/pdf_renamed/Fy4JAAAAQAAJ.pdf \
			 ../data/pdf_renamed/YAZXAAAAcAAJ.pdf \
			 ../data/pdf_renamed/8AQoAAAAYAAJ.pdf \
			 ../data/pdf_renamed/J4knAAAAMAAJ.pdf \
			 ../data/pdf_renamed/2jMfAAAAMAAJ.pdf \
			 ../data/pdf_renamed/u4cnAAAAMAAJ.pdf \
			 ../data/pdf_renamed/4zQfAAAAMAAJ.pdf \
			 ../data/pdf_renamed/WjMfAAAAMAAJ.pdf \
			 ../data/pdf_renamed/zviTtwEACAAJ.pdf \
			 ../data/pdf_renamed/zDTMtgEACAAJ.pdf \
			 ../data/pdf_renamed/quentindurward01scotuoft.pdf \
			 ../data/pdf_renamed/quentindurward02scotuoft.pdf \
			 ../data/pdf_renamed/chroniclesofcano02scot.pdf \
			 ../data/pdf_renamed/chroniclesofcano03scot.pdf \
			 ../data/pdf_renamed/anneofgeierstein02scot.pdf \
			 ../data/pdf_renamed/anneofgeierstein03scot.pdf \
			 ../data/pdf_renamed/XtEyAQAAMAAJ.pdf \
			 ../data/pdf_renamed/8dAyAQAAMAAJ.pdf \
			 ../data/pdf_renamed/oNEyAQAAMAAJ.pdf \
			 ../data/pdf_renamed/t88yAQAAMAAJ.pdf \
			 ../data/pdf_renamed/aNQwAQAAMAAJ.pdf \
			 ../data/pdf_renamed/htQwAQAAMAAJ.pdf \
			 ../data/pdf_renamed/DNUwAQAAMAAJ.pdf \
			../data/pdf_renamed/H9UwAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/HCRMAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/3pVMAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/D5pMAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/7JVMAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/AdiKyqdlp4cC.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/_QgOAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/fAoOAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/wggOAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/kggOAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/PzMJAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/1VUJAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/rDUJAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/MzQJAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/Fy4JAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/YAZXAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/8AQoAAAAYAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/J4knAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/2jMfAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/u4cnAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/4zQfAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/WjMfAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/zviTtwEACAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/zDTMtgEACAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/quentindurward01scotuoft.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/quentindurward02scotuoft.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/chroniclesofcano02scot.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/chroniclesofcano03scot.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/anneofgeierstein02scot.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/anneofgeierstein03scot.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/XtEyAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/8dAyAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/oNEyAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/t88yAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/aNQwAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/htQwAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/DNUwAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/H9UwAQAAMAAJ.pdf


xml_output: ../data/xml_output/HCRMAAAAcAAJ.xml \
			../data/xml_output/3pVMAAAAcAAJ.xml \
			../data/xml_output/D5pMAAAAcAAJ.xml \
			../data/xml_output/7JVMAAAAcAAJ.xml \
			../data/xml_output/AdiKyqdlp4cC.xml \
			../data/xml_output/_QgOAAAAQAAJ.xml \
			../data/xml_output/fAoOAAAAQAAJ.xml \
			../data/xml_output/wggOAAAAQAAJ.xml \
			../data/xml_output/kggOAAAAQAAJ.xml \
			../data/xml_output/PzMJAAAAQAAJ.xml \
			../data/xml_output/1VUJAAAAQAAJ.xml \
			../data/xml_output/rDUJAAAAQAAJ.xml \
			../data/xml_output/MzQJAAAAQAAJ.xml \
			../data/xml_output/Fy4JAAAAQAAJ.xml \
			../data/xml_output/YAZXAAAAcAAJ.xml \
			../data/xml_output/8AQoAAAAYAAJ.xml \
			../data/xml_output/J4knAAAAMAAJ.xml \
			../data/xml_output/2jMfAAAAMAAJ.xml \
			../data/xml_output/u4cnAAAAMAAJ.xml \
			../data/xml_output/4zQfAAAAMAAJ.xml \
			../data/xml_output/WjMfAAAAMAAJ.xml \
			../data/xml_output/zviTtwEACAAJ.xml \
			../data/xml_output/zDTMtgEACAAJ.xml \
			../data/xml_output/quentindurward01scotuoft.xml \
			../data/xml_output/quentindurward02scotuoft.xml \
			../data/xml_output/chroniclesofcano02scot.xml \
			../data/xml_output/chroniclesofcano03scot.xml \
			../data/xml_output/anneofgeierstein02scot.xml \
			../data/xml_output/anneofgeierstein03scot.xml \
			../data/xml_output/XtEyAQAAMAAJ.xml \
			../data/xml_output/8dAyAQAAMAAJ.xml \
			../data/xml_output/oNEyAQAAMAAJ.xml \
			../data/xml_output/t88yAQAAMAAJ.xml \
			../data/xml_output/aNQwAQAAMAAJ.xml \
			../data/xml_output/htQwAQAAMAAJ.xml \
			../data/xml_output/DNUwAQAAMAAJ.xml \
			../data/xml_output/H9UwAQAAMAAJ.xml 
	echo "done."
	
../data/xml_output/HCRMAAAAcAAJ.xml : ../data/pdf_renamed/HCRMAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/HCRMAAAAcAAJ.pdf

../data/xml_output/3pVMAAAAcAAJ.xml : ../data/pdf_renamed/3pVMAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/3pVMAAAAcAAJ.pdf

../data/xml_output/D5pMAAAAcAAJ.xml : ../data/pdf_renamed/D5pMAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/D5pMAAAAcAAJ.pdf

../data/xml_output/7JVMAAAAcAAJ.xml : ../data/pdf_renamed/7JVMAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/7JVMAAAAcAAJ.pdf

../data/xml_output/AdiKyqdlp4cC.xml : ../data/pdf_renamed/AdiKyqdlp4cC.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/AdiKyqdlp4cC.pdf

../data/xml_output/_QgOAAAAQAAJ.xml : ../data/pdf_renamed/_QgOAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/_QgOAAAAQAAJ.pdf

../data/xml_output/fAoOAAAAQAAJ.xml : ../data/pdf_renamed/fAoOAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/fAoOAAAAQAAJ.pdf

../data/xml_output/wggOAAAAQAAJ.xml : ../data/pdf_renamed/wggOAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/wggOAAAAQAAJ.pdf

../data/xml_output/kggOAAAAQAAJ.xml : ../data/pdf_renamed/kggOAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/kggOAAAAQAAJ.pdf

../data/xml_output/PzMJAAAAQAAJ.xml : ../data/pdf_renamed/PzMJAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/PzMJAAAAQAAJ.pdf

../data/xml_output/1VUJAAAAQAAJ.xml : ../data/pdf_renamed/1VUJAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/1VUJAAAAQAAJ.pdf

../data/xml_output/rDUJAAAAQAAJ.xml : ../data/pdf_renamed/rDUJAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/rDUJAAAAQAAJ.pdf

../data/xml_output/MzQJAAAAQAAJ.xml : ../data/pdf_renamed/MzQJAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/MzQJAAAAQAAJ.pdf

../data/xml_output/Fy4JAAAAQAAJ.xml : ../data/pdf_renamed/Fy4JAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/Fy4JAAAAQAAJ.pdf

../data/xml_output/YAZXAAAAcAAJ.xml : ../data/pdf_renamed/YAZXAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/YAZXAAAAcAAJ.pdf

../data/xml_output/8AQoAAAAYAAJ.xml : ../data/pdf_renamed/8AQoAAAAYAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/8AQoAAAAYAAJ.pdf

../data/xml_output/J4knAAAAMAAJ.xml : ../data/pdf_renamed/J4knAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/J4knAAAAMAAJ.pdf

../data/xml_output/2jMfAAAAMAAJ.xml : ../data/pdf_renamed/2jMfAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/2jMfAAAAMAAJ.pdf

../data/xml_output/u4cnAAAAMAAJ.xml : ../data/pdf_renamed/u4cnAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/u4cnAAAAMAAJ.pdf

../data/xml_output/4zQfAAAAMAAJ.xml : ../data/pdf_renamed/4zQfAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/4zQfAAAAMAAJ.pdf

../data/xml_output/WjMfAAAAMAAJ.xml : ../data/pdf_renamed/WjMfAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/WjMfAAAAMAAJ.pdf

../data/xml_output/zviTtwEACAAJ.xml : ../data/pdf_renamed/zviTtwEACAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/zviTtwEACAAJ.pdf

../data/xml_output/zDTMtgEACAAJ.xml : ../data/pdf_renamed/zDTMtgEACAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/zDTMtgEACAAJ.pdf

../data/xml_output/quentindurward01scotuoft.xml : ../data/pdf_renamed/quentindurward01scotuoft.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/quentindurward01scotuoft.pdf

../data/xml_output/quentindurward02scotuoft.xml : ../data/pdf_renamed/quentindurward02scotuoft.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/quentindurward02scotuoft.pdf

../data/xml_output/chroniclesofcano02scot.xml : ../data/pdf_renamed/chroniclesofcano02scot.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/chroniclesofcano02scot.pdf

../data/xml_output/chroniclesofcano03scot.xml : ../data/pdf_renamed/chroniclesofcano03scot.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/chroniclesofcano03scot.pdf

../data/xml_output/anneofgeierstein02scot.xml : ../data/pdf_renamed/anneofgeierstein02scot.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/anneofgeierstein02scot.pdf

../data/xml_output/anneofgeierstein03scot.xml : ../data/pdf_renamed/anneofgeierstein03scot.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/anneofgeierstein03scot.pdf

../data/xml_output/XtEyAQAAMAAJ.xml : ../data/pdf_renamed/XtEyAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/XtEyAQAAMAAJ.pdf

../data/xml_output/8dAyAQAAMAAJ.xml : ../data/pdf_renamed/8dAyAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/8dAyAQAAMAAJ.pdf

../data/xml_output/oNEyAQAAMAAJ.xml : ../data/pdf_renamed/oNEyAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/oNEyAQAAMAAJ.pdf

../data/xml_output/t88yAQAAMAAJ.xml : ../data/pdf_renamed/t88yAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/t88yAQAAMAAJ.pdf

../data/xml_output/aNQwAQAAMAAJ.xml : ../data/pdf_renamed/aNQwAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/aNQwAQAAMAAJ.pdf

../data/xml_output/htQwAQAAMAAJ.xml : ../data/pdf_renamed/htQwAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/htQwAQAAMAAJ.pdf

../data/xml_output/DNUwAQAAMAAJ.xml : ../data/pdf_renamed/DNUwAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/DNUwAQAAMAAJ.pdf

../data/xml_output/H9UwAQAAMAAJ.xml : ../data/pdf_renamed/H9UwAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/H9UwAQAAMAAJ.pdf

