pair_output: ../data/page_transcriptions/HCRMAAAAcAAJ.xml \
			 ../data/page_transcriptions/3pVMAAAAcAAJ.xml \
			 ../data/page_transcriptions/D5pMAAAAcAAJ.xml \
			 ../data/page_transcriptions/7JVMAAAAcAAJ.xml \
			 ../data/page_transcriptions/AdiKyqdlp4cC.xml \
			 ../data/page_transcriptions/_QgOAAAAQAAJ.xml \
			 ../data/page_transcriptions/fAoOAAAAQAAJ.xml \
			 ../data/page_transcriptions/wggOAAAAQAAJ.xml \
			 ../data/page_transcriptions/kggOAAAAQAAJ.xml \
			 ../data/page_transcriptions/PzMJAAAAQAAJ.xml \
			 ../data/page_transcriptions/1VUJAAAAQAAJ.xml \
			 ../data/page_transcriptions/rDUJAAAAQAAJ.xml \
			 ../data/page_transcriptions/MzQJAAAAQAAJ.xml \
			 ../data/page_transcriptions/Fy4JAAAAQAAJ.xml \
			 ../data/page_transcriptions/YAZXAAAAcAAJ.xml \
			 ../data/page_transcriptions/8AQoAAAAYAAJ.xml \
			 ../data/page_transcriptions/J4knAAAAMAAJ.xml \
			 ../data/page_transcriptions/2jMfAAAAMAAJ.xml \
			 ../data/page_transcriptions/u4cnAAAAMAAJ.xml \
			 ../data/page_transcriptions/4zQfAAAAMAAJ.xml \
			 ../data/page_transcriptions/WjMfAAAAMAAJ.xml \
			 ../data/page_transcriptions/zviTtwEACAAJ.xml \
			 ../data/page_transcriptions/zDTMtgEACAAJ.xml \
			 ../data/page_transcriptions/quentindurward01scotuoft.xml \
			 ../data/page_transcriptions/quentindurward02scotuoft.xml \
			 ../data/page_transcriptions/chroniclesofcano02scot.xml \
			 ../data/page_transcriptions/chroniclesofcano03scot.xml \
			 ../data/page_transcriptions/anneofgeierstein02scot.xml \
			 ../data/page_transcriptions/anneofgeierstein03scot.xml \
			 ../data/page_transcriptions/XtEyAQAAMAAJ.xml \
			 ../data/page_transcriptions/8dAyAQAAMAAJ.xml \
			 ../data/page_transcriptions/oNEyAQAAMAAJ.xml \
			 ../data/page_transcriptions/t88yAQAAMAAJ.xml \
			 ../data/page_transcriptions/aNQwAQAAMAAJ.xml \
			 ../data/page_transcriptions/htQwAQAAMAAJ.xml \
			 ../data/page_transcriptions/DNUwAQAAMAAJ.xml \
			 ../data/page_transcriptions/H9UwAQAAMAAJ.xml \
			 ../data/pdf_renamed/HCRMAAAAcAAJ.pdf \
			 ../data/pdf_renamed/3pVMAAAAcAAJ.pdf \
			 ../data/pdf_renamed/D5pMAAAAcAAJ.pdf \
			 ../data/pdf_renamed/7JVMAAAAcAAJ.pdf \
			 ../data/pdf_renamed/AdiKyqdlp4cC.pdf \
			 ../data/pdf_renamed/_QgOAAAAQAAJ.pdf \
			 ../data/pdf_renamed/fAoOAAAAQAAJ.pdf \
			 ../data/pdf_renamed/wggOAAAAQAAJ.pdf \
			 ../data/pdf_renamed/kggOAAAAQAAJ.pdf \
			 ../data/pdf_renamed/PzMJAAAAQAAJ.pdf \
			 ../data/pdf_renamed/1VUJAAAAQAAJ.pdf \
			 ../data/pdf_renamed/rDUJAAAAQAAJ.pdf \
			 ../data/pdf_renamed/MzQJAAAAQAAJ.pdf \
			 ../data/pdf_renamed/Fy4JAAAAQAAJ.pdf \
			 ../data/pdf_renamed/YAZXAAAAcAAJ.pdf \
			 ../data/pdf_renamed/8AQoAAAAYAAJ.pdf \
			 ../data/pdf_renamed/J4knAAAAMAAJ.pdf \
			 ../data/pdf_renamed/2jMfAAAAMAAJ.pdf \
			 ../data/pdf_renamed/u4cnAAAAMAAJ.pdf \
			 ../data/pdf_renamed/4zQfAAAAMAAJ.pdf \
			 ../data/pdf_renamed/WjMfAAAAMAAJ.pdf \
			 ../data/pdf_renamed/zviTtwEACAAJ.pdf \
			 ../data/pdf_renamed/zDTMtgEACAAJ.pdf \
			 ../data/pdf_renamed/quentindurward01scotuoft.pdf \
			 ../data/pdf_renamed/quentindurward02scotuoft.pdf \
			 ../data/pdf_renamed/chroniclesofcano02scot.pdf \
			 ../data/pdf_renamed/chroniclesofcano03scot.pdf \
			 ../data/pdf_renamed/anneofgeierstein02scot.pdf \
			 ../data/pdf_renamed/anneofgeierstein03scot.pdf \
			 ../data/pdf_renamed/XtEyAQAAMAAJ.pdf \
			 ../data/pdf_renamed/8dAyAQAAMAAJ.pdf \
			 ../data/pdf_renamed/oNEyAQAAMAAJ.pdf \
			 ../data/pdf_renamed/t88yAQAAMAAJ.pdf \
			 ../data/pdf_renamed/aNQwAQAAMAAJ.pdf \
			 ../data/pdf_renamed/htQwAQAAMAAJ.pdf \
			 ../data/pdf_renamed/DNUwAQAAMAAJ.pdf \
			../data/pdf_renamed/H9UwAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/HCRMAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/3pVMAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/D5pMAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/7JVMAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/AdiKyqdlp4cC.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/_QgOAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/fAoOAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/wggOAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/kggOAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/PzMJAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/1VUJAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/rDUJAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/MzQJAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/Fy4JAAAAQAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/YAZXAAAAcAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/8AQoAAAAYAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/J4knAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/2jMfAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/u4cnAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/4zQfAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/WjMfAAAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/zviTtwEACAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/zDTMtgEACAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/quentindurward01scotuoft.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/quentindurward02scotuoft.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/chroniclesofcano02scot.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/chroniclesofcano03scot.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/anneofgeierstein02scot.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/anneofgeierstein03scot.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/XtEyAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/8dAyAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/oNEyAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/t88yAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/aNQwAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/htQwAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/DNUwAQAAMAAJ.pdf
	python extract_pair_dataset.py --pdf_path ../data/pdf_renamed/H9UwAQAAMAAJ.pdf


page_transcriptions: ../data/page_transcriptions/HCRMAAAAcAAJ.xml \
			../data/page_transcriptions/3pVMAAAAcAAJ.xml \
			../data/page_transcriptions/D5pMAAAAcAAJ.xml \
			../data/page_transcriptions/7JVMAAAAcAAJ.xml \
			../data/page_transcriptions/AdiKyqdlp4cC.xml \
			../data/page_transcriptions/_QgOAAAAQAAJ.xml \
			../data/page_transcriptions/fAoOAAAAQAAJ.xml \
			../data/page_transcriptions/wggOAAAAQAAJ.xml \
			../data/page_transcriptions/kggOAAAAQAAJ.xml \
			../data/page_transcriptions/PzMJAAAAQAAJ.xml \
			../data/page_transcriptions/1VUJAAAAQAAJ.xml \
			../data/page_transcriptions/rDUJAAAAQAAJ.xml \
			../data/page_transcriptions/MzQJAAAAQAAJ.xml \
			../data/page_transcriptions/Fy4JAAAAQAAJ.xml \
			../data/page_transcriptions/YAZXAAAAcAAJ.xml \
			../data/page_transcriptions/8AQoAAAAYAAJ.xml \
			../data/page_transcriptions/J4knAAAAMAAJ.xml \
			../data/page_transcriptions/2jMfAAAAMAAJ.xml \
			../data/page_transcriptions/u4cnAAAAMAAJ.xml \
			../data/page_transcriptions/4zQfAAAAMAAJ.xml \
			../data/page_transcriptions/WjMfAAAAMAAJ.xml \
			../data/page_transcriptions/zviTtwEACAAJ.xml \
			../data/page_transcriptions/zDTMtgEACAAJ.xml \
			../data/page_transcriptions/quentindurward01scotuoft.xml \
			../data/page_transcriptions/quentindurward02scotuoft.xml \
			../data/page_transcriptions/chroniclesofcano02scot.xml \
			../data/page_transcriptions/chroniclesofcano03scot.xml \
			../data/page_transcriptions/anneofgeierstein02scot.xml \
			../data/page_transcriptions/anneofgeierstein03scot.xml \
			../data/page_transcriptions/XtEyAQAAMAAJ.xml \
			../data/page_transcriptions/8dAyAQAAMAAJ.xml \
			../data/page_transcriptions/oNEyAQAAMAAJ.xml \
			../data/page_transcriptions/t88yAQAAMAAJ.xml \
			../data/page_transcriptions/aNQwAQAAMAAJ.xml \
			../data/page_transcriptions/htQwAQAAMAAJ.xml \
			../data/page_transcriptions/DNUwAQAAMAAJ.xml \
			../data/page_transcriptions/H9UwAQAAMAAJ.xml 
	echo "done."
	
../data/page_transcriptions/HCRMAAAAcAAJ.xml : ../data/pdf_renamed/HCRMAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/HCRMAAAAcAAJ.pdf

../data/page_transcriptions/3pVMAAAAcAAJ.xml : ../data/pdf_renamed/3pVMAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/3pVMAAAAcAAJ.pdf

../data/page_transcriptions/D5pMAAAAcAAJ.xml : ../data/pdf_renamed/D5pMAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/D5pMAAAAcAAJ.pdf

../data/page_transcriptions/7JVMAAAAcAAJ.xml : ../data/pdf_renamed/7JVMAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/7JVMAAAAcAAJ.pdf

../data/page_transcriptions/AdiKyqdlp4cC.xml : ../data/pdf_renamed/AdiKyqdlp4cC.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/AdiKyqdlp4cC.pdf

../data/page_transcriptions/_QgOAAAAQAAJ.xml : ../data/pdf_renamed/_QgOAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/_QgOAAAAQAAJ.pdf

../data/page_transcriptions/fAoOAAAAQAAJ.xml : ../data/pdf_renamed/fAoOAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/fAoOAAAAQAAJ.pdf

../data/page_transcriptions/wggOAAAAQAAJ.xml : ../data/pdf_renamed/wggOAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/wggOAAAAQAAJ.pdf

../data/page_transcriptions/kggOAAAAQAAJ.xml : ../data/pdf_renamed/kggOAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/kggOAAAAQAAJ.pdf

../data/page_transcriptions/PzMJAAAAQAAJ.xml : ../data/pdf_renamed/PzMJAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/PzMJAAAAQAAJ.pdf

../data/page_transcriptions/1VUJAAAAQAAJ.xml : ../data/pdf_renamed/1VUJAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/1VUJAAAAQAAJ.pdf

../data/page_transcriptions/rDUJAAAAQAAJ.xml : ../data/pdf_renamed/rDUJAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/rDUJAAAAQAAJ.pdf

../data/page_transcriptions/MzQJAAAAQAAJ.xml : ../data/pdf_renamed/MzQJAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/MzQJAAAAQAAJ.pdf

../data/page_transcriptions/Fy4JAAAAQAAJ.xml : ../data/pdf_renamed/Fy4JAAAAQAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/Fy4JAAAAQAAJ.pdf

../data/page_transcriptions/YAZXAAAAcAAJ.xml : ../data/pdf_renamed/YAZXAAAAcAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/YAZXAAAAcAAJ.pdf

../data/page_transcriptions/8AQoAAAAYAAJ.xml : ../data/pdf_renamed/8AQoAAAAYAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/8AQoAAAAYAAJ.pdf

../data/page_transcriptions/J4knAAAAMAAJ.xml : ../data/pdf_renamed/J4knAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/J4knAAAAMAAJ.pdf

../data/page_transcriptions/2jMfAAAAMAAJ.xml : ../data/pdf_renamed/2jMfAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/2jMfAAAAMAAJ.pdf

../data/page_transcriptions/u4cnAAAAMAAJ.xml : ../data/pdf_renamed/u4cnAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/u4cnAAAAMAAJ.pdf

../data/page_transcriptions/4zQfAAAAMAAJ.xml : ../data/pdf_renamed/4zQfAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/4zQfAAAAMAAJ.pdf

../data/page_transcriptions/WjMfAAAAMAAJ.xml : ../data/pdf_renamed/WjMfAAAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/WjMfAAAAMAAJ.pdf

../data/page_transcriptions/zviTtwEACAAJ.xml : ../data/pdf_renamed/zviTtwEACAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/zviTtwEACAAJ.pdf

../data/page_transcriptions/zDTMtgEACAAJ.xml : ../data/pdf_renamed/zDTMtgEACAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/zDTMtgEACAAJ.pdf

../data/page_transcriptions/quentindurward01scotuoft.xml : ../data/pdf_renamed/quentindurward01scotuoft.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/quentindurward01scotuoft.pdf

../data/page_transcriptions/quentindurward02scotuoft.xml : ../data/pdf_renamed/quentindurward02scotuoft.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/quentindurward02scotuoft.pdf

../data/page_transcriptions/chroniclesofcano02scot.xml : ../data/pdf_renamed/chroniclesofcano02scot.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/chroniclesofcano02scot.pdf

../data/page_transcriptions/chroniclesofcano03scot.xml : ../data/pdf_renamed/chroniclesofcano03scot.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/chroniclesofcano03scot.pdf

../data/page_transcriptions/anneofgeierstein02scot.xml : ../data/pdf_renamed/anneofgeierstein02scot.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/anneofgeierstein02scot.pdf

../data/page_transcriptions/anneofgeierstein03scot.xml : ../data/pdf_renamed/anneofgeierstein03scot.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/anneofgeierstein03scot.pdf

../data/page_transcriptions/XtEyAQAAMAAJ.xml : ../data/pdf_renamed/XtEyAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/XtEyAQAAMAAJ.pdf

../data/page_transcriptions/8dAyAQAAMAAJ.xml : ../data/pdf_renamed/8dAyAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/8dAyAQAAMAAJ.pdf

../data/page_transcriptions/oNEyAQAAMAAJ.xml : ../data/pdf_renamed/oNEyAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/oNEyAQAAMAAJ.pdf

../data/page_transcriptions/t88yAQAAMAAJ.xml : ../data/pdf_renamed/t88yAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/t88yAQAAMAAJ.pdf

../data/page_transcriptions/aNQwAQAAMAAJ.xml : ../data/pdf_renamed/aNQwAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/aNQwAQAAMAAJ.pdf

../data/page_transcriptions/htQwAQAAMAAJ.xml : ../data/pdf_renamed/htQwAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/htQwAQAAMAAJ.pdf

../data/page_transcriptions/DNUwAQAAMAAJ.xml : ../data/pdf_renamed/DNUwAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/DNUwAQAAMAAJ.pdf

../data/page_transcriptions/H9UwAQAAMAAJ.xml : ../data/pdf_renamed/H9UwAQAAMAAJ.pdf ../data/sheet/corpus-scott-shakespeare-translations.tsv
	python create_xml_files.py --pdf_path ../data/pdf_renamed/H9UwAQAAMAAJ.pdf

